include:
  template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - release
  - docs

unit:
  image: node:8
  stage: test
  script:
    - npm install
    - npm run test
  artifacts:
    paths:
    - coverage
    - report
  only:
  - develop

tag:
  before_script:
    - npm install --frozen-lockfile
  image: node:8
  stage: release
  script:
    - npx semantic-delivery-gitlab --token ${GITLAB_TOKEN}
  artifacts:
    paths:
    - dist
  only:
  - master

publish:
  before_script:
    - npm install --frozen-lockfile
  image: node:8
  stage: release
  script:
    - npm run build-lib
    - npx npm-publish-git-tag --access public
  only:
  - tags

pages:
  image: node:8
  stage: docs
  script:
    - npm install
    - npm run styleguide:build
    - rm -rf ./public
    - mv styleguide public
  artifacts:
    paths:
    - public
  only:
  - master
